### ISSUE TITLE
正文里的粗体不易区分

### ISSUE THREAD

**Issue by Kzinux** [liungkejin/liungkejin.github.io#5]
首先要感谢梁兄写出这么美观简洁的博客，方便我等菜鸟fork下就可以入驻写博了。  
博客各方面都很满意，就是用markdown语法####标明的标题跟正文字体差不多粗细，不容易区分。
下图中的第一行就是标题，下面两行是正文。

![blog](https://user-images.githubusercontent.com/7030257/26923159-d2bb38b8-4c73-11e7-8e4c-53b5256b1175.png)

**Comment by liungkejin** [comment]
那就少加个 ```#``` ，然后用 ```**XX**``` 加粗，哈哈

**Comment by Kzinux** [comment]
少加个#字体又太大了，而且####已经是粗体了，在本地用markdown渲染软件Remarkable看是明显的粗体，上传到博客后就变细了。  
用firefox的开发者工具看是bootstrap.min.css里的一句样式导致的。 
```css
.h1, .h2, .h3, .h4, .h5, .h6, h1, h2, h3, h4, h5, h6 {
    font-family: inherit;
    font-weight: 500;
    line-height: 1.1;
    color: inherit;
}
```
